import { test } from "node:test"
import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"

test("Plugin only emits routable invitation Relay QR payloads", async () => {
  const indexSource = await readFile(new URL("../src/index.js", import.meta.url), "utf8")
  const panelSource = await readFile(new URL("../src/module2.js", import.meta.url), "utf8")
  const cryptoSource = await readFile(new URL("../src/relay/crypto.js", import.meta.url), "utf8")

  assert.match(indexSource, /relayPairSnapshot\(state\.relay\)/)
  assert.match(cryptoSource, /const snap = \{ v: 2, client, routeId, routeSecret \}/)
  assert.doesNotMatch(cryptoSource, /snap\.controlUrl/)
  assert.doesNotMatch(indexSource, /relay-qr-mode|qrMode|["']anonymous["']/)
  assert.doesNotMatch(panelSource, /relay-qr-mode|qrMode|setQrMode|["']anonymous["']/)
  assert.match(panelSource, /接入码来自 Relay 控制台/)
  assert.match(indexSource, /\/dsh-link\/relay-reconnect/)
  assert.match(panelSource, /重新连接/)
  assert.match(indexSource, /\/dsh-link\/relay-release/)
  assert.match(panelSource, /释放名额/)
  assert.match(indexSource, /applyRelayRouteRevoked/)
  assert.match(indexSource, /resumeOnFailure/)
  assert.match(panelSource, /换到别的 Relay 会先确认/)
  assert.match(indexSource, /confirmRelaySwitch/)
  assert.match(indexSource, /previousRelayReleaseTarget/)
  assert.match(indexSource, /previousReleased/)
  assert.match(indexSource, /\/dsh-link\/relay-ack-replaced/)
  assert.match(panelSource, /relay_switch/)
  assert.match(panelSource, /尝试从原控制台移除/)
  assert.doesNotMatch(panelSource, /\/v1\/tenants|oauth|signup/)
  assert.match(panelSource, /打开控制台/)
  assert.match(indexSource, /rememberReplacedRelayControlURL/)
  assert.match(panelSource, /打开原控制台/)
  assert.doesNotMatch(cryptoSource, /snap\.replacedRelayControlUrl/)
  assert.doesNotMatch(cryptoSource, /snap\.pairStamp/)
  assert.match(indexSource, /pairStamp: cloudPairStamp\(state\.relay\)/)
  assert.match(panelSource, /&r=\$\{encodeURIComponent\(stamp\)\}/)
  assert.match(panelSource, /stamp: relay\?\.pairStamp/)
  assert.match(indexSource, /routeRotated/)
  assert.match(indexSource, /attachRelayControlUrl\(state\.relay, controlUrl, derived\.agentAddress\)/)
  assert.match(panelSource, /parsedEnroll\?\.controlUrl/)
  assert.match(panelSource, /if \(!res\.ok\) \{\s*await load\(\)\.catch/s)
  assert.match(panelSource, /纯远程请重新扫云端配对码/)
  assert.match(panelSource, /手机不登录控制台/)
  assert.match(panelSource, /showCloudPairQR/)
  assert.match(panelSource, /连上后即可扫这张云端码/)
  assert.doesNotMatch(panelSource, /online\s*\?\s*jsx\(PairCard/)
})
