// Command loadgen drives DLR/1 capacity measurements against a local relay
// instance. It models real usage — a handful of long-lived streams per route
// doing periodic request/response roundtrips — not connection churn, because
// the pre-auth per-IP limiter (burst 32 / 30m) intentionally throttles churn.
// Concurrency comes from multiple enrolled hosts (routes), each opening up to
// default_max_streams_per_route streams.
//
// Usage (against an isolated local instance):
//
//	loadgen -agent 127.0.0.1:9444 -client 127.0.0.1:9443 \
//	  -admin http://127.0.0.1:8081 -admin-user admin \
//	  -admin-pass-file <file> -hosts 8 -streams 8 -duration 5m
package main

import (
	"bytes"
	"crypto/tls"
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/http/cookiejar"
	"os"
	"os/exec"
	"sort"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/dsh-links/dsh-links-relay/internal/cryptoutil"
	"github.com/dsh-links/dsh-links-relay/internal/protocol"
	"github.com/dsh-links/dsh-links-relay/internal/testkit"
)

// tlsDial connects to the relay's real TLS data plane. The capacity instance
// uses a self-signed certificate generated by init, so verification is
// skipped for this local lab tool; production clients pin the fingerprint.
func tlsDial(network, addr string, timeout time.Duration) (net.Conn, error) {
	d := &net.Dialer{Timeout: timeout}
	return tls.DialWithDialer(d, network, addr, &tls.Config{InsecureSkipVerify: true}) // lab only
}

type result struct {
	DurationSec      float64 `json:"duration_sec"`
	Hosts            int     `json:"hosts"`
	StreamsPerHost   int     `json:"streams_per_host"`
	PeakActive       int     `json:"peak_active_streams"`
	Reconnects       int64   `json:"stream_reconnects"`
	Roundtrips       int64   `json:"roundtrips"`
	Errors           int64   `json:"errors"`
	ErrorRatePct     float64 `json:"error_rate_pct"`
	PayloadBytes     int     `json:"payload_bytes"`
	ThroughputMBps   float64 `json:"echo_throughput_mbps"`
	RTTP50Ms         float64 `json:"rtt_p50_ms"`
	RTTP95Ms         float64 `json:"rtt_p95_ms"`
	RTTP99Ms         float64 `json:"rtt_p99_ms"`
	RTTMaxMs         float64 `json:"rtt_max_ms"`
	RSSStartKB       int64   `json:"relay_rss_start_kb"`
	RSSPeakKB        int64   `json:"relay_rss_peak_kb"`
	Samples          int     `json:"samples"`
	FirstErrorSample string  `json:"first_error,omitempty"`
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "loadgen: "+format+"\n", args...)
	os.Exit(1)
}

func main() {
	agentAddr := flag.String("agent", "127.0.0.1:9444", "relay agent listen address")
	clientAddr := flag.String("client", "127.0.0.1:9443", "relay client listen address")
	adminURL := flag.String("admin", "http://127.0.0.1:8081", "control admin base URL")
	adminUser := flag.String("admin-user", "admin", "admin user")
	adminPassFile := flag.String("admin-pass-file", "", "file containing the admin password")
	hosts := flag.Int("hosts", 8, "number of hosts (routes) to enroll")
	streams := flag.Int("streams", 8, "concurrent streams per host")
	duration := flag.Duration("duration", 3*time.Minute, "measurement window")
	payload := flag.Int("payload", 8192, "roundtrip payload bytes")
	interval := flag.Duration("interval", time.Second, "pacing between roundtrips per stream")
	rampPS := flag.Float64("ramp-ps", 4, "stream starts per second")
	pid := flag.Int("pid", 0, "relay process id for RSS sampling (0=off)")
	out := flag.String("out", "", "write summary JSON to this file")
	flag.Parse()

	if *adminPassFile == "" {
		fatal("-admin-pass-file is required")
	}
	passBytes, err := os.ReadFile(*adminPassFile)
	if err != nil {
		fatal("read admin password: %v", err)
	}
	adminPass := strings.TrimSpace(string(passBytes))

	inviteCodes := make([]string, *hosts)
	for i := range inviteCodes {
		code, err := createInvite(*adminURL, *adminUser, adminPass)
		if err != nil {
			fatal("create invite %d: %v", i, err)
		}
		inviteCodes[i] = code
		time.Sleep(250 * time.Millisecond) // enrollLimiter is burst 6 / 2s
	}

	echoAddr, closeEcho := testkit.StartEchoServer()
	defer closeEcho()

	// hostIds persist in control's SQLite across instance restarts; make them
	// unique per loadgen run so re-enroll is never rejected as re-registration.
	runId := fmt.Sprintf("t%d", time.Now().UnixNano()%1_000_000)
	agents := make([]*testkit.SimAgent, *hosts)
	for i := 0; i < *hosts; i++ {
		_, priv, err := cryptoutil.GenerateEd25519KeyPair()
		if err != nil {
			fatal("keygen host %d: %v", i, err)
		}
		ag := testkit.NewSimAgent(*agentAddr, fmt.Sprintf("loadgen-%s-host-%d", runId, i), priv, echoAddr)
		ag.Dial = tlsDial
		// enrollLimiter is capacity 6 with refill 2/min, so a batch larger than
		// the burst (or recent prior runs) needs backoff-and-retry.
		var enrollErr error
		for attempt := 0; attempt < 8; attempt++ {
			enrollErr = ag.Enroll(inviteCodes[i])
			if enrollErr == nil {
				break
			}
			time.Sleep(32 * time.Second)
		}
		if enrollErr != nil {
			fatal("enroll host %d: %v", i, enrollErr)
		}
		agents[i] = ag
		go func(a *testkit.SimAgent) {
			if err := a.Register(); err != nil {
				fmt.Fprintf(os.Stderr, "agent %s register ended: %v\n", a.HostId, err)
			}
		}(ag)
		time.Sleep(700 * time.Millisecond) // enrollLimiter burst 6: keep well under refill
	}
	fmt.Printf("enrolled %d hosts; opening %d streams/host (%d total), window %s\n",
		*hosts, *streams, *hosts**streams, *duration)

	var (
		roundtrips  atomic.Int64
		reconnects  atomic.Int64
		errors      atomic.Int64
		active      atomic.Int64
		peakActive  atomic.Int64
		echoedBytes atomic.Int64
		mu          sync.Mutex
		rtts        []float64
		firstErr    string
	)
	recordError := func(err error) {
		errors.Add(1)
		mu.Lock()
		if firstErr == "" {
			firstErr = err.Error()
		}
		mu.Unlock()
	}

	end := time.Now().Add(*duration)
	start := time.Now()
	rssStart := sampleRSS(*pid)

	var wg sync.WaitGroup
	startTicker := time.NewTicker(time.Duration(float64(time.Second) / *rampPS))
	defer startTicker.Stop()
	started := 0
	for h := 0; h < *hosts; h++ {
		for s := 0; s < *streams; s++ {
			<-startTicker.C
			if time.Now().After(end) {
				break
			}
			started++
			wg.Add(1)
			active.Add(1)
			go func(routeId, routeSecret string) {
				defer wg.Done()
				defer active.Add(-1)
				buf := make([]byte, *payload)
				first := true
				for time.Now().Before(end) {
					if !first {
						reconnects.Add(1)
					}
					first = false
					conn, err := connectStream(*clientAddr, routeId, routeSecret)
					if err != nil {
						recordError(err)
						sleepUnlessEnd(end, 2*time.Second)
						continue
					}
					seq := int64(0)
					for time.Now().Before(end) {
						binary.PutVarint(buf[:8], seq)
						rttStart := time.Now()
						_ = conn.SetWriteDeadline(time.Now().Add(5 * time.Second))
						if _, err := conn.Write(buf); err != nil {
							recordError(err)
							break
						}
						if err := readFull(conn, buf); err != nil {
							recordError(err)
							break
						}
						rttMs := float64(time.Since(rttStart).Microseconds()) / 1000.0
						mu.Lock()
						rtts = append(rtts, rttMs)
						mu.Unlock()
						roundtrips.Add(1)
						echoedBytes.Add(int64(*payload))
						seq++
						sleepUnlessEnd(end, *interval)
					}
					conn.Close()
					sleepUnlessEnd(end, 500*time.Millisecond)
				}
			}(agents[h].GetRouteId(), agents[h].GetRouteSecret())
		}
	}

	sampleStop := make(chan struct{})
	go func() {
		ticker := time.NewTicker(time.Second)
		defer ticker.Stop()
		for {
			select {
			case <-sampleStop:
				return
			case <-ticker.C:
				cur := active.Load()
				for {
					p := peakActive.Load()
					if cur <= p || peakActive.CompareAndSwap(p, cur) {
						break
					}
				}
				elapsed := time.Since(start).Seconds()
				mbps := float64(echoedBytes.Load()) / 1e6 / elapsed
				fmt.Printf("[%5.0fs] active=%d roundtrips=%d err=%d echo=%.2fMB/s rss=%s\n",
					elapsed, cur, roundtrips.Load(), errors.Load(), mbps, rssString(*pid))
			}
		}
	}()

	wg.Wait()
	close(sampleStop)

	rssPeak := maxRSS()
	res := result{
		DurationSec:    time.Since(start).Seconds(),
		Hosts:          *hosts,
		StreamsPerHost: *streams,
		PeakActive:     int(peakActive.Load()),
		Reconnects:     reconnects.Load(),
		Roundtrips:     roundtrips.Load(),
		Errors:         errors.Load(),
		PayloadBytes:   *payload,
		ThroughputMBps: float64(echoedBytes.Load()) / 1e6 / time.Since(start).Seconds(),
		RTTP50Ms:       percentile(rtts, 50),
		RTTP95Ms:       percentile(rtts, 95),
		RTTP99Ms:       percentile(rtts, 99),
		RTTMaxMs:       percentile(rtts, 100),
		RSSStartKB:     rssStart,
		RSSPeakKB:      rssPeak,
		Samples:        len(rtts),
	}
	if total := res.Roundtrips + res.Errors; total > 0 {
		res.ErrorRatePct = float64(res.Errors) / float64(total) * 100
	}
	if firstErr != "" {
		if len(firstErr) > 200 {
			firstErr = firstErr[:200]
		}
		res.FirstErrorSample = firstErr
	}

	summary, _ := json.MarshalIndent(res, "", "  ")
	fmt.Println(string(summary))
	if *out != "" {
		if err := os.WriteFile(*out, summary, 0o600); err != nil {
			fatal("write summary: %v", err)
		}
	}
	for _, ag := range agents {
		ag.Close()
	}
}

// connectStream performs one CONNECT → READY handshake and returns the raw
// bridged connection (bytes are echoed by the agent-side echo target).
func connectStream(clientAddr, routeId, routeSecret string) (net.Conn, error) {
	conn, err := tlsDial("tcp", clientAddr, 5*time.Second)
	if err != nil {
		return nil, err
	}
	fr := protocol.NewFrameReader(conn)
	_ = conn.SetReadDeadline(time.Now().Add(5 * time.Second))
	helloRaw, err := fr.ReadFrame(protocol.MaxHello)
	if err != nil {
		conn.Close()
		return nil, fmt.Errorf("hello: %w", err)
	}
	var hello protocol.HelloFrame
	if err := json.Unmarshal(helloRaw, &hello); err != nil {
		conn.Close()
		return nil, err
	}
	chal, err := base64.RawURLEncoding.DecodeString(hello.Challenge)
	if err != nil {
		conn.Close()
		return nil, err
	}
	routeRaw, _ := base64.RawURLEncoding.DecodeString(routeId)
	secretRaw, _ := base64.RawURLEncoding.DecodeString(routeSecret)
	nonce, _ := cryptoutil.GenerateNonce()
	ts := time.Now().Unix()
	transcript := cryptoutil.BuildMACTranscript("CONNECT", routeRaw, nil, nil, ts, nonce, chal)
	mac := cryptoutil.ComputeMAC(secretRaw, transcript)
	frame := protocol.ConnectFrame{
		Type:  protocol.TypeConnect,
		Route: routeId,
		Ts:    ts,
		Nonce: base64.RawURLEncoding.EncodeToString(nonce),
		Mac:   base64.RawURLEncoding.EncodeToString(mac),
	}
	b, _ := json.Marshal(frame)
	_ = conn.SetWriteDeadline(time.Now().Add(5 * time.Second))
	if _, err := conn.Write(append(b, '\n')); err != nil {
		conn.Close()
		return nil, err
	}
	_ = conn.SetReadDeadline(time.Now().Add(10 * time.Second))
	raw, err := fr.ReadFrame(protocol.MaxReady)
	if err != nil {
		conn.Close()
		return nil, fmt.Errorf("ready: %w", err)
	}
	var ready protocol.ReadyFrame
	if err := json.Unmarshal(raw, &ready); err != nil {
		var e protocol.ErrorFrame
		if json.Unmarshal(raw, &e) == nil && e.Type == "ERROR" {
			conn.Close()
			return nil, fmt.Errorf("relay error %s", e.Code)
		}
		conn.Close()
		return nil, err
	}
	if ready.Type != protocol.TypeReady {
		conn.Close()
		return nil, fmt.Errorf("expected READY got %s", ready.Type)
	}
	_ = conn.SetReadDeadline(time.Time{})
	return conn, nil
}

func readFull(conn net.Conn, buf []byte) error {
	total := 0
	for total < len(buf) {
		_ = conn.SetReadDeadline(time.Now().Add(10 * time.Second))
		n, err := conn.Read(buf[total:])
		if n > 0 {
			total += n
		}
		if err != nil {
			if total == len(buf) {
				return nil
			}
			return err
		}
	}
	return nil
}

func sleepUnlessEnd(end time.Time, d time.Duration) {
	remaining := time.Until(end)
	if remaining <= 0 {
		time.Sleep(50 * time.Millisecond)
		return
	}
	if d > remaining {
		d = remaining
	}
	time.Sleep(d)
}

func percentile(sorted []float64, p float64) float64 {
	if len(sorted) == 0 {
		return 0
	}
	s := append([]float64(nil), sorted...)
	sort.Float64s(s)
	idx := int(float64(len(s)-1) * p / 100)
	return s[idx]
}

func createInvite(adminURL, user, pass string) (string, error) {
	jar, err := cookiejar.New(nil)
	if err != nil {
		return "", err
	}
	client := &http.Client{Jar: jar, Timeout: 10 * time.Second}
	body := bytes.NewReader([]byte(fmt.Sprintf(`{"user":%q,"password":%q}`, user, pass)))
	req, err := http.NewRequest(http.MethodPost, adminURL+"/login", body)
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(io.LimitReader(resp.Body, 200))
		return "", fmt.Errorf("login %d: %s", resp.StatusCode, b)
	}
	invResp, err := client.Post(adminURL+"/v1/invites", "application/json", bytes.NewReader([]byte("{}")))
	if err != nil {
		return "", err
	}
	defer invResp.Body.Close()
	if invResp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(io.LimitReader(invResp.Body, 200))
		return "", fmt.Errorf("invite %d: %s", invResp.StatusCode, b)
	}
	var out struct {
		InviteCode string `json:"inviteCode"`
	}
	if err := json.NewDecoder(invResp.Body).Decode(&out); err != nil {
		return "", err
	}
	if out.InviteCode == "" {
		return "", fmt.Errorf("empty invite code")
	}
	return out.InviteCode, nil
}

func sampleRSS(pid int) int64 {
	if pid <= 0 {
		return 0
	}
	return psRSS(pid)
}

var rssPeakSeen int64

func maxRSS() int64 { return rssPeakSeen }

func rssString(pid int) string {
	if pid <= 0 {
		return "n/a"
	}
	rss := psRSS(pid)
	if rss > rssPeakSeen {
		rssPeakSeen = rss
	}
	return fmt.Sprintf("%dkb", rss)
}

func psRSS(pid int) int64 {
	if pid <= 0 {
		return 0
	}
	out, err := osExec("ps", "-o", "rss=", "-p", fmt.Sprint(pid))
	if err != nil {
		return 0
	}
	var rss int64
	fmt.Sscanf(strings.TrimSpace(out), "%d", &rss)
	return rss
}

func osExec(name string, args ...string) (string, error) {
	cmd := exec.Command(name, args...)
	out, err := cmd.Output()
	if err != nil {
		return "", err
	}
	return string(out), nil
}
